# Build Phase
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
COPY .env .env 

RUN npm install
COPY . .

RUN npm run build

# Serve phase
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY EXE201_FE/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
