server {
    listen 80;
    server_name gundam.thanhnt-tech.id.vn;

    root /usr/share/nginx/html;
    index index.html;

    # Ưu tiên serve file JS, CSS, ảnh,... đúng MIME type
    location ~* \.(?:js|css|ico|gif|jpe?g|png|woff2?|ttf|svg|eot)$ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }

    # App route fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css application/json;
    gzip_min_length 1000;
}
