name: CI/CD Pipeline

on:
  push:
    branches: [FE_khanhTran] # Hoặc branch bạn dùng để deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install & Build FE (in EXE201_FE)
        working-directory: EXE201_FE
        run: |
          npm install
          npm run build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image (FE)
        run: |
          docker build -t nguyentanthanh1403/exe_pre_order_fe:latest ./EXE201_FE
          docker tag nguyentanthanh1403/exe_pre_order_fe:latest nguyentanthanh1403/exe_pre_order_fe:${{ github.sha }}
          docker push nguyentanthanh1403/exe_pre_order_fe:latest
          docker push nguyentanthanh1403/exe_pre_order_fe:${{ github.sha }}

      - name: Deploy to Google VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: thanhnt.tech
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/thanhnt.tech/EXE_PreOrder/FE
            docker compose stop preOrder-frontend || true
            docker compose rm -f preOrder-frontend || true
            docker compose pull
            docker compose up -d preOrder-frontend
